### ISSUE TITLE
jenkins.ros.org keep failing with Groovy

### ISSUE THREAD

**Issue by k-okada** [start-jsk/openrtm_aist_core#23] opened 2014-03-07 05:00 UTC
http://jenkins.ros.org/job/ros-groovy-openrtm-aist_binarydeb_precise_amd64/32/console

**Comment by k-okada** [comment] 2014-03-07 05:01
depends on mk (#22) seems ok

**Comment by k-okada** [comment] 2014-03-07 05:05
I'm just confused, we need depends on "rosbuild"

**Comment by k-okada** [comment] 2014-03-07 05:15
see https://github.com/start-jsk/openhrp3/pull/25 for openhrp3

**Comment by 130s** [comment] 2014-03-07 06:39
https://github.com/start-jsk/openrtm_aist_core/issues/24 is merged. Let's see if this works in a [pre-release test](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/1/console).

**Comment by 130s** [comment] 2014-03-07 07:15
[pre-release test](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/1/console) failed in its downstream build section -- openrtm_aist_core itself seems to be built. So I'll re-release it (by incrementing build version as always).

**Comment by 130s** [comment] 2014-03-07 07:32
Just updated the title since I found it's only failing with Groovy
http://www.ros.org/debbuild/hydro.html?q=openrtm even though version is the
same 1.1.0-1. There might be changes that are only available in hydro
upstream dependency that fix the issue.

**Comment by k-okada** [comment] 2014-03-07 07:44
Humm, not a good sign..

http://jenkins.ros.org/job/prerelease-hydro-openrtm_aist_core/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/1/consoleFull

**Comment by 130s** [comment] 2014-03-07 07:58
Pre-release test failure is always not very good, but it CAN happen -- downstream build checking in the pre-release tests use `released` codes from release repository (see http://wiki.ros.org/regression_tests#Prerelease_Tests for the detail), meaning there can be inconsistency between the package that's tested and those that were released awhile ago and not necessarily adjusted to the change you're just about to release.

For example, in this particular case:
- `openrtm_aist_core` 1.1.0-2 is what we're about to release.
- `hrpsys_ros_bridge` 1.0.5 was released months ago and this is where downstream check is failing.

There CAN be inconsistency between `hrpsys_ros_bridge` and `openrtm_aist_core`, and that's where we need more caffeine/beer to work it out!

**Comment by 130s** [comment] 2014-03-08 07:32
Now `openrtm_aist_core` (and its direct dependant `openhrp3`) on Groovy builds with build versions `1.1.0-4`, `3.1.5-5`, respectively.

**Closed as completed by 130s** 2014-03-08 07:32 UTC
